### ISSUE TITLE
Migrate Data Visualisation module

### ISSUE THREAD

**Issue by tanyagray** [digital-skills-for-researchers/coursebook#47]
Data Visualisation module should now be called Python Data Visualisation.

Module needs:
- index page with learning outcomes, lessons section, badges
- badge pages for existing badges

Lessons to be created at a later date.

**Comment by sarahmaygray** [comment]
- Renamed to python-data-visualisation. 
- Example badge created. 
- Additional resources copied to index page for reviewing. 
- ipython-notebook copied over with no modification.
